# Generated by Django 2.1.2 on 2018-10-15 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='이름', max_length=20)),
                ('title', models.CharField(db_column='제목', max_length=50)),
                ('text', models.TextField(db_column='내용', help_text='텍스트', max_length=150)),
                ('update_date', models.DateTimeField()),
                ('priority', models.BooleanField(db_column='중요')),
            ],
        ),
    ]
