# Generated by Django 2.1.2 on 2018-10-15 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='강의제목', max_length=50)),
                ('text', models.TextField(db_column='가격 등 내용', help_text='텍스트', max_length=150)),
                ('discount', models.TextField(db_column='할인율', max_length=20)),
                ('update_date', models.DateTimeField(db_column='수집날짜')),
            ],
        ),
        migrations.DeleteModel(
            name='Portal',
        ),
    ]
