# Generated by Django 2.1.2 on 2018-10-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_price_is_publish'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='price',
            name='category',
            field=models.CharField(default='기존', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price',
            name='link',
            field=models.TextField(default='Null'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price',
            name='name',
            field=models.CharField(default='Null', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price',
            name='price',
            field=models.PositiveIntegerField(default='0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price',
            name='summary',
            field=models.TextField(default='Null'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='price',
            name='discount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='price',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='price',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='price',
            name='update_date',
            field=models.DateTimeField(),
        ),
    ]
