# Generated by Django 2.1.2 on 2018-10-19 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_remove_price_update_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='is_publish',
        ),
    ]
