# Generated by Django 2.1.2 on 2018-10-21 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_remove_price_is_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='update_date',
            field=models.DateTimeField(default='2018-10-21'),
            preserve_default=False,
        ),
    ]
