# Generated by Django 2.1.2 on 2018-10-26 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_auto_20181026_1711'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['-update_date', 'id']},
        ),
    ]
