# Generated by Django 2.1.2 on 2018-11-07 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_auto_20181026_1718'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['-update_date', '-id']},
        ),
    ]
