"""
Django settings for askcompany project.

Generated by 'django-admin startproject' using Django 2.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
#__file__은 settings.py의 경로를 절대경로로 바꾸고, 부모 경로를 의미함
# 이러면, manage.py가 있는 폴더가 경로가 됨

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '+5mpel(66bb+!v2t3-r39%g6*m$)z(v&mi!mtk*8db1syrep57'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*',
]
#    '127.0.0.1', 
#    'ahnbu.pythonanywhere.com',
#    ]


# Application definition

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.humanize',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'shop',
    'mylotto',
    'memo_app',
    'portal',
    'blog',

    'django_extensions',
    'debug_toolbar',
    'mathfilters',
    'django_jinja',

    'django.contrib.admin',
]

MIDDLEWARE = [
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'askcompany.urls'

TEMPLATES = [
    {
        "BACKEND": "django_jinja.backend.Jinja2",
        "APP_DIRS": True, #장고기본jinja에서는 사용불가했지만, 여기서는 지원 가능
        "OPTIONS": {
            "match_extension": ".j2", #어떤 확장자에 대해서 jinja 백엔드 지원할 수 있게 됨
            'context_processors': [ 
                "django.contrib.auth.context_processors.auth", #user를 확인해줌
                "django.template.context_processors.debug",
                "django.template.context_processors.i18n",
                "django.template.context_processors.media",
                "django.template.context_processors.static",
                "django.template.context_processors.tz",
                "django.contrib.messages.context_processors.messages",
            ],
        }
    },
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates', # 템플릿엔진
        'DIRS': [
            os.path.join(BASE_DIR, 'askcompany','templates'),
            # 1개 정도만 지정하면 됨, 하위 askcomany폴더안에 있다는 의미
        ], #프로젝트 레벨의 템플릿을 둘 디렉토리
        'APP_DIRS': True, #앱별 템플릿 경로 추가 여부
        'OPTIONS': {
            'context_processors': [ 
                #템플릿 내 디폴트 참조할 변수목록 제공하는 함수, request받고, dict를 반환
                #모든 템플릿에 디폴트로 로딩이 필요한 함수의 경우 지정하는 곳.
                # render가 될때마다, 아래 함수 처리후 템플릿에 넘겨줌. 
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'askcompany.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'

# 추가했음
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'askcompany', 'static'),
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

INTERNAL_IPS = ['127.0.0.1']

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    # 기존 로깅 설정을 무시하지 않고 사용하겠다.
    'filters': {
        'require_debug_true': {
        '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'filters': ['require_debug_true'],
            # settings에서 Debug가 켜있을 경우에만 동작
            'class': 'logging.StreamHandler',
        },
        'write_to_file': {
            'level': 'DEBUG',
            'filters': ['require_debug_true'],
            # settings에서 Debug가 켜있을 경우에만 동작
            'class': 'logging.FileHandler',
            'filename': 'db.log',
        },
    },
    'loggers': {
        'django.db.backends': {
            'handlers': ['console', 'write_to_file'],
            # console을 설정하면 server화면에 계속 출력
            # db.log라는 파일에 해당 내용을 저장
            'level': 'DEBUG',
        },
        'shop':{
            'handlers': ['console'],
            'level': 'DEBUG', 
        },
        'portal':{
            'handlers': ['console'],
            'level': 'DEBUG', 
        }
    }
}