# Generated by Django 2.1.2 on 2018-11-08 06:12

import askcompany.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_item_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='photo',
            field=models.ImageField(blank=True, upload_to=askcompany.utils.uuid_upload_to),
        ),
    ]
